package com.shadow.desafio.service.exceptions;

public class UserNotFoundException extends RuntimeException {


}
